version: '3.8'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload --workers 1
    image: observerly/perseus:latest
    container_name: observerly_perseus
    restart: always
    ports:
      - 8001:5000
    volumes: 
      - ./:/usr/src/app
    links:
      - redis:redis
    env_file:
      - .env
    networks:
      - api

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always
    networks:
      - api

networks:
  api:
    name: api
    driver: bridge