version: '3.8'

services:
  api:
    build: .
    command:
      - "/usr/src/app/start.sh"
    image: observerly/perseus:latest
    container_name: observerly_perseus
    restart: always
    ports:
      - 8001:5000
    volumes: 
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
    links:
      - redis:redis
    env_file:
      - .env
    networks:
      - api

  db: 
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - web

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always
    networks:
      - api

volumes:
  db:
    driver: local

networks:
  web:
    name: web
  api:
    name: api
    driver: bridge