version: '3.8'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload --workers 1
    image: observerly/perseus:latest
    container_name: observerly_perseus
    restart: always
    ports:
      - 8001:5000
    volumes: 
      - .:/app
    depends_on:
      - db
    links:
      - db:db
      - redis:redis
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/init_pgtrgm_extension.sql:/docker-entrypoint-initdb.d/init_pgtrgm_extension.sql
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always

volumes:
    postgres_data: