"""feat: Added Body model (e.g., Star, Galaxy, Nebulae etc.)

Revision ID: f3b35e23e6d7
Revises: 
Create Date: 2023-02-03 13:12:46.606928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b35e23e6d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True, comment='Common or IAU Name'),
    sa.Column('iau', sa.String(length=180), nullable=True, comment='IAU Name'),
    sa.Column('ra', sa.Float(precision=10, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Right Ascension of the central point of the Body'),
    sa.Column('dec', sa.Float(precision=10, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Declination of the central point of the Body'),
    sa.Column('constellation', sa.String(length=180), nullable=True, comment='IAU Constellation (Contained Within)'),
    sa.Column('type', sa.String(length=180), nullable=True, comment='Celestial Body Type e.g., Star, Spiral Galaxy etc'),
    sa.Column('apparent_magnitude', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Apparent Magnitude (m)'),
    sa.Column('absolute_magnitude', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Absolute Magnitude (M)'),
    sa.Column('distance', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Distance (in parsecs, pc)'),
    sa.Column('hd', sa.String(length=180), nullable=True, comment='Henry Draper (HD) Catalogue Number'),
    sa.Column('hr', sa.String(length=180), nullable=True, comment='Harvard Revised (HR) Catalogue Number'),
    sa.Column('hip', sa.String(length=180), nullable=True, comment='Hipparcos (HIP) Catalogue Number'),
    sa.Column('bd', sa.String(length=180), nullable=True, comment='Hipparcos (HIP) Catalogue Number'),
    sa.Column('flamsteed', sa.String(length=10), nullable=True, comment='Flamsteed Catalogue Number'),
    sa.Column('messier', sa.String(length=3), nullable=True, comment='Messier Catalogue Number'),
    sa.Column('ngc', sa.String(length=12), nullable=True, comment='New General Catalogue (NGC) Number'),
    sa.Column('ic', sa.String(length=12), nullable=True, comment='Indexed Catalogue (IC) Number'),
    sa.Column('eccentricity', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Eccentricity (e)'),
    sa.Column('semi_major_axis', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Semi-major axis (a)'),
    sa.Column('semi_minor_axis', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Semi-minor axis (b)'),
    sa.Column('inclination', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Inclination (i)'),
    sa.Column('redshift', sa.Float(precision=5, asdecimal=True, decimal_return_scale=10), nullable=True, comment='Redshift (z)'),
    sa.Column('simbad', sa.String(length=200), nullable=True, comment='SIMBAD Search Query URL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_body_bd'), 'body', ['bd'], unique=False)
    op.create_index(op.f('ix_body_constellation'), 'body', ['constellation'], unique=False)
    op.create_index(op.f('ix_body_flamsteed'), 'body', ['flamsteed'], unique=False)
    op.create_index(op.f('ix_body_hd'), 'body', ['hd'], unique=False)
    op.create_index(op.f('ix_body_hip'), 'body', ['hip'], unique=False)
    op.create_index(op.f('ix_body_hr'), 'body', ['hr'], unique=False)
    op.create_index(op.f('ix_body_iau'), 'body', ['iau'], unique=False)
    op.create_index(op.f('ix_body_ic'), 'body', ['ic'], unique=False)
    op.create_index(op.f('ix_body_messier'), 'body', ['messier'], unique=False)
    op.create_index(op.f('ix_body_name'), 'body', ['name'], unique=False)
    op.create_index(op.f('ix_body_ngc'), 'body', ['ngc'], unique=False)
    op.create_index(op.f('ix_body_type'), 'body', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_type'), table_name='body')
    op.drop_index(op.f('ix_body_ngc'), table_name='body')
    op.drop_index(op.f('ix_body_name'), table_name='body')
    op.drop_index(op.f('ix_body_messier'), table_name='body')
    op.drop_index(op.f('ix_body_ic'), table_name='body')
    op.drop_index(op.f('ix_body_iau'), table_name='body')
    op.drop_index(op.f('ix_body_hr'), table_name='body')
    op.drop_index(op.f('ix_body_hip'), table_name='body')
    op.drop_index(op.f('ix_body_hd'), table_name='body')
    op.drop_index(op.f('ix_body_flamsteed'), table_name='body')
    op.drop_index(op.f('ix_body_constellation'), table_name='body')
    op.drop_index(op.f('ix_body_bd'), table_name='body')
    op.drop_table('body')
    # ### end Alembic commands ###