global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: web

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: INFO
  format: common


entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecured
          scheme: https

  websecured:
    address: ":443"