name: perseus/ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '__pycache__'
      - '.pytest_cache'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: CI/CD Build & Test w/pytest
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    env:
      PROJECT_NAME: "Perseus FastAPI"
      FIRST_SUPERUSER_EMAIL: ${{ secrets.FIRST_SUPERUSER_EMAIL }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_SERVER: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SERVER_NAME: "perseus"
      SERVER_HOST: "https://perseus.observerly.com"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Compose Build
        run: docker compose -f local.yml up -d --build

      - name: Bash Exec Docker Compose
        run: docker compose -f local.yml exec api bash